import continuous_geometries_geometric_closure_systems_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace continuous_geometries_geometric_closure_systems_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end continuous_geometries_geometric_closure_systems_theorem_canonical_lane_mathlib
end HautevilleHouse
